---
title: "data Import"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

lets import a dataset

```{r}
litters_df = 
  read.csv("data_import_examples/FAS_litters.csv")
```


look at data

```{r}
names(litters_df)
```



```{r}
litters_df =
  janitor::clean_names(litters_df)
```

```{r}
litters_df
```

```{r}
skimr::skim(litters_df)
```

##fix the missing data

```{r}
read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", ""))
```

## IMport Pups Data

```{r}
pups_df =
  read_csv("data_import_examples/FAS_pups.csv",
           skip = 3,
          na = c("NA", ".", "")
          )

pups_df = 
  janitor::clean_names(pups_df)
```


## OKay what about excel

CSVs are really great but sometimes you get an excel file.


```{r}
mlb_df = 
  read_excel("data_import_examples/mlb11.xlsx")
```

Import LOTR Word COunts

```{r}
fotr_df = 
  read_excel("data_import_examples/LotR_Words.xlsx", range = "B3:D6")
```

#SAS?????

import pulse dataset

```{r}
pulse_df =
  read_sas("data_import_examples/public_pulse_data.sas7bdat")

pulse_df = 
  janitor::clean_names(pulse_df)
```

### why do i hate read.csv so much??

```{r, eval = FALSE}
litters_df_base = 
  read.csv("data_import_examples/FAS_litters.csv")
```

What about exporting?

```{r}
write_csv(fotr_df, "data_import_examples/fotr_df.csv")
```